import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { mkdirSync } from 'node:fs'

async function createPlan(page: Page) {
  await page.goto('/')
  await expect(page.getByRole('status')).toContainText('云端 AI 未配置')
  await page.getByLabel('主体与关系', { exact: true }).fill('女生')
  await page.getByRole('button', { name: '确认当前意图' }).click()
  await page.getByRole('button', { name: '我有一段剧本' }).click()
  await page.locator('#composer textarea').first().fill('女生抬手擦窗。')
  await page.getByRole('button', { name: '本地规则拆镜', exact: true }).click()
  await expect(page.locator('.shot-card')).toHaveCount(1)
}
test('edit shots, change route, restore version and reload saved project', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await createPlan(page)
  await page.getByLabel('起始姿态 / 物体状态', { exact: true }).fill('右手放在膝上')
  await page.locator('#result').getByLabel('结束画面', { exact: true }).fill('右手停在窗边')
  await page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true }).fill('缓慢抬起右手')
  await expect(page.locator('.prompt-block').first()).toContainText('右手放在膝上')
  await expect(page.locator('.prompt-block.accent')).toContainText('缓慢抬起右手')
  await page.getByRole('button', { name: '文生视频', exact: false }).filter({ has: page.locator('strong') }).click()
  await page.getByText('方案版本与对比', { exact: false }).click()
  await page.getByLabel('版本名称').fill('抬手方案')
  await page.getByRole('button', { name: '保存当前版本' }).click()
  await page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true }).fill('转头看窗外')
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true })).toHaveValue('缓慢抬起右手')
  await page.getByRole('button', { name: '保存项目', exact: true }).click()
  await page.reload()
  await expect(page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true })).toHaveValue('缓慢抬起右手')
  expect(errors).toEqual([])
})
test('bind reference purpose, export execution pack and roundtrip project JSON', async ({ page }) => {
  await createPlan(page)
  await page.locator('#assets>summary').click()
  await page.locator('.asset-upload input').setInputFiles({ name: 'character.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1sAAAAASUVORK5CYII=', 'base64') })
  await expect(page.locator('.asset-card')).toHaveCount(1)
  await page.locator('.shot-reference').click()
  await page.locator('.reference-role-list select').selectOption('first-frame')
  await expect(page.locator('.preflight-review')).not.toContainText('未绑定首帧')
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: '导出生成执行包' }).click()
  const file = await download; const text = await readFile((await file.path())!, 'utf8')
  expect(text).toContain('character.png'); expect(text).toContain('用途：首帧'); expect(text).toContain('入口：待确认')
  const jsonDownload = page.waitForEvent('download'); await page.getByRole('button', { name: '导出项目 JSON' }).click()
  const bundle = await jsonDownload
  await page.locator('.project-import input').setInputFiles((await bundle.path())!)
  await expect(page.locator('.reference-role-list select')).toHaveValue('first-frame')
  await expect(page.locator('.shot-reference.active')).toHaveCount(1)
})
test('static mode keeps local editing and disables cloud actions', async ({ page }) => {
  await page.route('**/api/health', route => route.fulfill({ status: 404, body: 'not found' }))
  await page.goto('/')
  await expect(page.getByRole('status')).toContainText('静态演示')
  await page.getByRole('button', { name: '本地规则拆镜', exact: true }).click()
  await expect(page.locator('.shot-card').first()).toBeVisible()
  await expect(page.getByRole('button', { name: '云端 AI 未就绪' }).first()).toBeDisabled()
  await page.getByRole('button', { name: '参考素材反推' }).click()
  await expect(page.getByRole('button', { name: '开始反推参考素材' })).toBeDisabled()
})
test('mobile layout fits viewport and captures reviewable screenshots', async ({ page }) => {
  mkdirSync('qa', { recursive: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await createPlan(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: 'qa/mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'qa/desktop-top.png' })
  await page.screenshot({ path: 'qa/desktop.png', fullPage: true })
})

test('cloud failure falls back using the original script only', async ({ page }) => {
  await page.route('**/api/health', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ aiConfigured: true, model: 'test-director' }) }))
  await page.route('**/api/director', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'AI_NOT_CONFIGURED' }) }))
  await page.goto('/')
  await expect(page.getByRole('status')).toContainText('云端 AI 已配置')
  await page.getByRole('button', { name: '我有一段剧本' }).click()
  await page.locator('#composer textarea').first().fill('女生抬手擦窗。')
  await page.getByRole('button', { name: '云端 AI 导演分析', exact: true }).click()
  await expect(page.locator('.shot-card')).toHaveCount(1)
  await expect(page.locator('.engine-status')).toContainText('Local Director')
})
