import { test, expect, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { mkdirSync } from 'node:fs'

async function createPlan(page: Page) {
  await page.goto('/')
  await expect(page.getByRole('status')).toContainText('云端 AI 未配置')
  await page.getByLabel('主体与关系', { exact: true }).fill('女生')
  await page.getByRole('button', { name: '确认当前意图' }).click()
  await page.getByRole('button', { name: '我有一段剧本' }).click()
  await page.locator('#composer textarea').first().fill('女生抬手擦窗。')
  await page.getByRole('button', { name: '本地规则拆镜', exact: true }).click()
  await expect(page.locator('.shot-card')).toHaveCount(1)
}
test('edit shots, change route, restore version and reload saved project', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await createPlan(page)
  await page.getByLabel('起始姿态 / 物体状态', { exact: true }).fill('右手放在膝上')
  await page.locator('#result').getByLabel('结束画面', { exact: true }).fill('右手停在窗边')
  await page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true }).fill('缓慢抬起右手')
  await expect(page.locator('.prompt-block').first()).toContainText('右手放在膝上')
  await expect(page.locator('.prompt-block.accent')).toContainText('缓慢抬起右手')
  await page.getByRole('button', { name: '文生视频', exact: false }).filter({ has: page.locator('strong') }).click()
  await page.getByText('方案版本与对比', { exact: false }).click()
  await page.getByLabel('版本名称').fill('抬手方案')
  await page.getByRole('button', { name: '保存当前版本' }).click()
  await page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true }).fill('转头看窗外')
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  await expect(page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true })).toHaveValue('缓慢抬起右手')
  await page.getByRole('button', { name: '保存项目', exact: true }).click()
  await page.reload()
  await expect(page.locator('#result').getByRole('textbox', { name: '动作过程', exact: true })).toHaveValue('缓慢抬起右手')
  expect(errors).toEqual([])
})
test('bind reference purpose, export execution pack and roundtrip project JSON', async ({ page }) => {
  await createPlan(page)
  await page.locator('#assets>summary').click()
  await page.locator('.asset-upload input').setInputFiles({ name: 'character.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1sAAAAASUVORK5CYII=', 'base64') })
  await expect(page.locator('.asset-card')).toHaveCount(1)
  await page.locator('.shot-reference').click()
  await page.locator('.reference-role-list select').selectOption('first-frame')
  await expect(page.locator('.preflight-review')).not.toContainText('未绑定首帧')
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: '导出生成执行包' }).click()
  const file = await download; const text = await readFile((await file.path())!, 'utf8')
  expect(text).toContain('character.png'); expect(text).toContain('用途：首帧'); expect(text).toContain('入口：待确认')
  const jsonDownload = page.waitForEvent('download'); await page.getByRole('button', { name: '导出项目 JSON' }).click()
  const bundle = await jsonDownload
  await page.locator('.project-import input').setInputFiles((await bundle.path())!)
  await expect(page.locator('.reference-role-list select')).toHaveValue('first-frame')
  await expect(page.locator('.shot-reference.active')).toHaveCount(1)
})
test('static mode keeps local editing and disables cloud actions', async ({ page }) => {
  await page.route('**/api/health', route => route.fulfill({ status: 404, body: 'not found' }))
  await page.goto('/')
  await expect(page.getByRole('status')).toContainText('静态演示')
  await page.getByRole('button', { name: '本地规则拆镜', exact: true }).click()
  await expect(page.locator('.shot-card').first()).toBeVisible()
  await expect(page.getByRole('button', { name: '云端 AI 未就绪' }).first()).toBeDisabled()
  await page.getByRole('button', { name: '参考素材反推' }).click()
  await expect(page.getByRole('button', { name: '开始反推参考素材' })).toBeDisabled()
})
test('mobile layout fits viewport and captures reviewable screenshots', async ({ page }) => {
  mkdirSync('qa', { recursive: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await createPlan(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: 'qa/mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'qa/desktop-top.png' })
  await page.screenshot({ path: 'qa/desktop.png', fullPage: true })
})

test('cloud failure falls back using the original script only', async ({ page }) => {
  await page.route('**/api/health', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ aiConfigured: true, model: 'test-director' }) }))
  await page.route('**/api/director', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'AI_NOT_CONFIGURED' }) }))
  await page.goto('/')
  await expect(page.getByRole('status')).toContainText('云端 AI 已配置')
  await page.getByRole('button', { name: '我有一段剧本' }).click()
  await page.locator('#composer textarea').first().fill('女生抬手擦窗。')
  await page.getByRole('button', { name: '云端 AI 导演分析', exact: true }).click()
  await expect(page.locator('.shot-card')).toHaveCount(1)
  await expect(page.locator('.engine-status')).toContainText('Local Director')
})

for (const width of [1440, 390]) {
  test(`all section links navigate before and after analysis at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/')
    const sections = ['brief', 'composer', 'assets', 'result', 'execution', 'versions']
    for (const id of sections) {
      await page.locator(`.workflow-nav a[href="#${id}"]`).click()
      await expect(page).toHaveURL(new RegExp(`#${id}$`))
      await expect(page.locator(`#${id}`)).toBeFocused()
      expect(await page.locator(`#${id}`).evaluate(el => el.getBoundingClientRect().top)).toBeGreaterThanOrEqual(68)
    }
    await expect(page.locator('#assets')).toHaveAttribute('open', '')
    await page.getByRole('button', { name: '开始创建方案' }).click()
    await expect(page).toHaveURL(/#composer$/)
    await createPlan(page)
    for (const id of sections) {
      await page.locator(`.workflow-nav a[href="#${id}"]`).click()
      await expect(page.locator(`#${id}`)).toBeFocused()
    }
    await expect(page.locator('#versions')).toHaveAttribute('open', '')
    await expect(page.getByLabel('版本名称')).toBeVisible()
    await page.reload()
    await expect(page.locator('#versions')).toHaveAttribute('open', '')
    await expect(page.locator('#versions')).toBeFocused()
  })
}

test('direct empty section links and browser history work', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#execution')
  await expect(page.locator('#execution')).toBeFocused()
  await expect(page.getByRole('button', { name: '先生成分镜方案' })).toBeVisible()
  await page.getByRole('button', { name: '先生成分镜方案' }).click()
  await expect(page).toHaveURL(/#composer$/)
  await page.goBack()
  await expect(page).toHaveURL(/#execution$/)
  await expect(page.locator('#execution')).toBeFocused()
})

test('same input tab preserves result and draft switching preserves text', async ({ page }) => {
  await createPlan(page)
  await page.getByRole('button', { name: '我有一段剧本' }).click()
  await expect(page.locator('.shot-card')).toHaveCount(1)
  await page.locator('#composer textarea').first().fill('我的剧本草稿')
  await page.getByRole('button', { name: '我有一个画面' }).click()
  await page.locator('#composer textarea').first().fill('我的画面草稿')
  await page.getByRole('button', { name: '我有一段剧本' }).click()
  await expect(page.locator('#composer textarea').first()).toHaveValue('我的剧本草稿')
  await page.getByRole('button', { name: '我有一个画面' }).click()
  await expect(page.locator('#composer textarea').first()).toHaveValue('我的画面草稿')
})

test('clipboard denial produces visible feedback, not an unhandled error', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { value: { writeText: () => Promise.reject(new Error('permission denied')) }, configurable: true }))
  await createPlan(page)
  await page.getByRole('button', { name: '复制全部', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('操作未完成')
  await expect(page.getByRole('alert')).toBeInViewport()
  await page.getByRole('button', { name: '关闭操作提示' }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: '分享当前方案' }).click()
  await expect(page.getByRole('alert')).toContainText('操作未完成')
  expect(errors).toEqual([])
})

test('shot controls and all export formats perform real actions', async ({ page }) => {
  await createPlan(page)
  await page.locator('.shot-edit-row').getByRole('button', { name: '复制', exact: true }).click()
  await expect(page.locator('.shot-card')).toHaveCount(2)
  await page.locator('.shot-edit-row input').first().fill('8')
  await expect(page.locator('.timeline-head')).toContainText('11s')
  await page.locator('.shot-edit-row').first().getByRole('button', { name: '删除', exact: true }).click()
  await expect(page.locator('.shot-card')).toHaveCount(1)
  await expect(page.locator('.shot-edit-row').getByRole('button', { name: '删除', exact: true })).toBeDisabled()
  for (const name of ['导出 MD', '导出 CSV', '导出项目 JSON', '导出生成执行包']) {
    const downloadPromise = page.waitForEvent('download')
    await page.getByRole('button', { name, exact: true }).click()
    const download = await downloadPromise
    expect((await readFile((await download.path())!, 'utf8')).length).toBeGreaterThan(20)
  }
  await page.getByRole('button', { name: '保存项目', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('已保存')
})

test('project create, switch and delete preserve saved plans', async ({ page }) => {
  await createPlan(page)
  await page.getByRole('button', { name: '保存项目', exact: true }).click()
  const savedId = await page.getByLabel('切换项目').inputValue()
  await page.getByRole('button', { name: '新建', exact: true }).click()
  await expect(page.locator('.shot-card')).toHaveCount(0)
  await expect(page.locator('#result')).toContainText('还没有分镜方案')
  const newId = await page.getByLabel('切换项目').inputValue()
  await page.getByLabel('切换项目').selectOption(savedId)
  await expect(page.locator('.shot-card')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '我有一段剧本' })).toHaveClass(/active/)
  await page.getByLabel('切换项目').selectOption(newId)
  await page.getByRole('button', { name: '删除当前项目' }).click()
  await expect(page.locator('.shot-card')).toHaveCount(1)
  await expect(page.getByLabel('切换项目').locator('option')).toHaveCount(1)
})

test('copy and scheme sharing return usable text snapshots', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await createPlan(page)
  await page.getByRole('button', { name: '复制全部', exact: true }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('SHOT 01')
  await page.getByRole('button', { name: '分享当前方案' }).click()
  const link = await page.evaluate(() => navigator.clipboard.readText())
  expect(link).toContain('#share=')
  await page.goto(link)
  await expect(page.locator('.shot-card')).toHaveCount(1)
  await expect(page.getByRole('alert')).toContainText('已打开分享方案')
  await page.locator('.workflow-nav a[href="#execution"]').click()
  await expect(page.locator('#execution')).toBeFocused()
})
